sudo: false
language: python
branches:
  except:
    - gh-pages
python:
  - "2.6"
  - "2.7"
addons:
  apt:
    packages:
    - build-essential
    - libzmq-dev
install: "pip install -r requirements/zeromq.txt -r requirements/tests.txt --use-mirrors"
script:
  nosetests --with-coverage --cover-package=beaver
after_success:
  coveralls
