sudo: false
language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
addons:
  apt:
    packages:
    - build-essential
    - libzmq-dev
install: "pip install -r requirements/zeromq.txt -r requirements/tests.txt --use-mirrors"
script: nosetests
